version: '3.7'

services:
  app:
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 1 -k gthread --thread=2 --log-level DEBUG --bind 0.0.0.0:8000 transup.wsgi"
