version: '3.7'

services:
  app:
    restart: always
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    build: .
    depends_on:
      - db

  db:
    image: postgres:11.4
    ports:
      - "5433:5432"
    volumes:
      - transup-data:/var/lib/postgresql/data

volumes:
  transup-data:
