version: '3.7'

services:
  app:
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 1 -k gthread --thread=2 --log-level DEBUG --bind 0.0.0.0:8000 transup.wsgi"

  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1001
      - PGID=10012
      - EMAIL=otseobande@gmail.com
      - URL=${URL}
      - TZ=America/NewYork
      - VALIDATION=http
    volumes:
      - ${HOME}/config:/config
      - ./nginx.conf:/config/nginx/site-confs/default
    depends_on:
      - app
