version: '3.7'

services:
  app:
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn -w 1 -k gthread --thread=2 --log-level DEBUG --bind 0.0.0.0:8000 transup.wsgi"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./transup/static/:/transup/static/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
