# Generated by Django 2.2.3 on 2019-07-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20190723_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created']},
        ),
    ]
